export const API = 'API';
export const SET_USER_INFO = 'SET_USER_INFO';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const RESET_USER_INFO = 'RESET_USER_INFO';

export const SET_ALL_PUBLICATIONS = 'SET_ALL_PUBLICATIONS';
export const ADD_PUBLICATION = 'ADD_PUBLICATION';
export const REMOVE_PUBLICATION = 'REMOVE_PUBLICATION';
export const UPDATE_PUBLICATION = 'UPDATE_PUBLICATION';
